// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFsl8KaEnEIbiCWPLHLODFKb4lIEMnZ3k',
    appId: '1:628131585034:web:ea721fc8892bbb91e493f3',
    messagingSenderId: '628131585034',
    projectId: 'tweet-or-kit',
    authDomain: 'tweet-or-kit.firebaseapp.com',
    storageBucket: 'tweet-or-kit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtonlx7oSTVf8ZJICwUGigPbR1ngKopXw',
    appId: '1:628131585034:android:efb656c3d6c52463e493f3',
    messagingSenderId: '628131585034',
    projectId: 'tweet-or-kit',
    storageBucket: 'tweet-or-kit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lVjuhuGMEtBGkZlKEAKiPPRsWygUwxo',
    appId: '1:628131585034:ios:e2d4c53b3c9c2990e493f3',
    messagingSenderId: '628131585034',
    projectId: 'tweet-or-kit',
    storageBucket: 'tweet-or-kit.firebasestorage.app',
    iosBundleId: 'com.example.tweetorkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lVjuhuGMEtBGkZlKEAKiPPRsWygUwxo',
    appId: '1:628131585034:ios:e2d4c53b3c9c2990e493f3',
    messagingSenderId: '628131585034',
    projectId: 'tweet-or-kit',
    storageBucket: 'tweet-or-kit.firebasestorage.app',
    iosBundleId: 'com.example.tweetorkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFsl8KaEnEIbiCWPLHLODFKb4lIEMnZ3k',
    appId: '1:628131585034:web:1c6988592f92df46e493f3',
    messagingSenderId: '628131585034',
    projectId: 'tweet-or-kit',
    authDomain: 'tweet-or-kit.firebaseapp.com',
    storageBucket: 'tweet-or-kit.firebasestorage.app',
  );

}